server:
    port: 8084
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: look
                  uri: lb://look
                  predicates:
                  - Path=/look/**
                - id: account
                  uri: lb://account
                  predicates:
                    - Path=/account/**